const puppeteer = require('puppeteer');
const fs = require('fs');

// List of URLs to scrape
const urls = ["https://www.python.org/downloads/release/python-3130/",
"https://www.python.org/downloads/release/python-3127/",
"https://www.python.org/downloads/release/python-31110/",
"https://www.python.org/downloads/release/python-31015/",
"https://www.python.org/downloads/release/python-3126/",
"https://www.python.org/downloads/release/python-3920/",
"https://www.python.org/downloads/release/python-3820/",
"https://www.python.org/downloads/release/python-3125/",
"https://www.python.org/downloads/release/python-3124/",
"https://www.python.org/downloads/release/python-3123/",
"https://www.python.org/downloads/release/python-3119/",
"https://www.python.org/downloads/release/python-31014/",
"https://www.python.org/downloads/release/python-3919/",
"https://www.python.org/downloads/release/python-3819/",
"https://www.python.org/downloads/release/python-3118/",
"https://www.python.org/downloads/release/python-3122/",
"https://www.python.org/downloads/release/python-3121/",
"https://www.python.org/downloads/release/python-3117/",
"https://www.python.org/downloads/release/python-3120/",
"https://www.python.org/downloads/release/python-3116/",
"https://www.python.org/downloads/release/python-3115/",
"https://www.python.org/downloads/release/python-31013/",
"https://www.python.org/downloads/release/python-3918/",
"https://www.python.org/downloads/release/python-3818/",
"https://www.python.org/downloads/release/python-31012/",
"https://www.python.org/downloads/release/python-3114/",
"https://www.python.org/downloads/release/python-3717/",
"https://www.python.org/downloads/release/python-3817/",
"https://www.python.org/downloads/release/python-3917/",
"https://www.python.org/downloads/release/python-31011/",
"https://www.python.org/downloads/release/python-3113/",
"https://www.python.org/downloads/release/python-31010/",
"https://www.python.org/downloads/release/python-3112/",
"https://www.python.org/downloads/release/python-3111/",
"https://www.python.org/downloads/release/python-3109/",
"https://www.python.org/downloads/release/python-3916/",
"https://www.python.org/downloads/release/python-3816/",
"https://www.python.org/downloads/release/python-3716/",
"https://www.python.org/downloads/release/python-3110/",
"https://www.python.org/downloads/release/python-3915/",
"https://www.python.org/downloads/release/python-3815/",
"https://www.python.org/downloads/release/python-3108/",
"https://www.python.org/downloads/release/python-3715/",
"https://www.python.org/downloads/release/python-3714/",
"https://www.python.org/downloads/release/python-3814/",
"https://www.python.org/downloads/release/python-3914/",
"https://www.python.org/downloads/release/python-3107/",
"https://www.python.org/downloads/release/python-3106/",
"https://www.python.org/downloads/release/python-3105/",
"https://www.python.org/downloads/release/python-3913/",
"https://www.python.org/downloads/release/python-3104/",
"https://www.python.org/downloads/release/python-3912/",
"https://www.python.org/downloads/release/python-3103/",
"https://www.python.org/downloads/release/python-3911/",
"https://www.python.org/downloads/release/python-3813/",
"https://www.python.org/downloads/release/python-3713/",
"https://www.python.org/downloads/release/python-3910/",
"https://www.python.org/downloads/release/python-3102/",
"https://www.python.org/downloads/release/python-3101/",
"https://www.python.org/downloads/release/python-399/",
"https://www.python.org/downloads/release/python-398/",
"https://www.python.org/downloads/release/python-3100/",
"https://www.python.org/downloads/release/python-3712/",
"https://www.python.org/downloads/release/python-3615/",
"https://www.python.org/downloads/release/python-397/",
"https://www.python.org/downloads/release/python-3812/",
"https://www.python.org/downloads/release/python-396/",
"https://www.python.org/downloads/release/python-3811/",
"https://www.python.org/downloads/release/python-3711/",
"https://www.python.org/downloads/release/python-3614/",
"https://www.python.org/downloads/release/python-395/",
"https://www.python.org/downloads/release/python-3810/",
"https://www.python.org/downloads/release/python-394/",
"https://www.python.org/downloads/release/python-389/",
"https://www.python.org/downloads/release/python-392/",
"https://www.python.org/downloads/release/python-388/",
"https://www.python.org/downloads/release/python-3613/",
"https://www.python.org/downloads/release/python-3710/",
"https://www.python.org/downloads/release/python-387/",
"https://www.python.org/downloads/release/python-391/",
"https://www.python.org/downloads/release/python-390/",
"https://www.python.org/downloads/release/python-386/",
"https://www.python.org/downloads/release/python-3510/",
"https://www.python.org/downloads/release/python-379/",
"https://www.python.org/downloads/release/python-3612/",
"https://www.python.org/downloads/release/python-385/",
"https://www.python.org/downloads/release/python-384/",
"https://www.python.org/downloads/release/python-378/",
"https://www.python.org/downloads/release/python-3611/",
"https://www.python.org/downloads/release/python-383/",
"https://www.python.org/downloads/release/python-2718/",
"https://www.python.org/downloads/release/python-377/",
"https://www.python.org/downloads/release/python-382/",
"https://www.python.org/downloads/release/python-381/",
"https://www.python.org/downloads/release/python-376/",
"https://www.python.org/downloads/release/python-3610/",
"https://www.python.org/downloads/release/python-359/",
"https://www.python.org/downloads/release/python-358/",
"https://www.python.org/downloads/release/python-2717/",
"https://www.python.org/downloads/release/python-375/",
"https://www.python.org/downloads/release/python-380/",
"https://www.python.org/downloads/release/python-374/",
"https://www.python.org/downloads/release/python-369/",
"https://www.python.org/downloads/release/python-373/",
"https://www.python.org/downloads/release/python-3410/",
"https://www.python.org/downloads/release/python-357/",
"https://www.python.org/downloads/release/python-2716/",
"https://www.python.org/downloads/release/python-372/",
"https://www.python.org/downloads/release/python-368/",
"https://www.python.org/downloads/release/python-371/",
"https://www.python.org/downloads/release/python-367/",
"https://www.python.org/downloads/release/python-356/",
"https://www.python.org/downloads/release/python-349/",
"https://www.python.org/downloads/release/python-370/",
"https://www.python.org/downloads/release/python-366/",
"https://www.python.org/downloads/release/python-2715/",
"https://www.python.org/downloads/release/python-365/",
"https://www.python.org/downloads/release/python-348/",
"https://www.python.org/downloads/release/python-355/",
"https://www.python.org/downloads/release/python-364/",
"https://www.python.org/downloads/release/python-363/",
"https://www.python.org/downloads/release/python-337/",
"https://www.python.org/downloads/release/python-2714/",
"https://www.python.org/downloads/release/python-347/",
"https://www.python.org/downloads/release/python-354/",
"https://www.python.org/downloads/release/python-362/",
"https://www.python.org/downloads/release/python-361/",
"https://www.python.org/downloads/release/python-346/",
"https://www.python.org/downloads/release/python-353/",
"https://www.python.org/downloads/release/python-360/",
"https://www.python.org/downloads/release/python-2713/",
"https://www.python.org/downloads/release/python-345/",
"https://www.python.org/downloads/release/python-352/",
"https://www.python.org/downloads/release/python-2712/",
"https://www.python.org/downloads/release/python-344/",
"https://www.python.org/downloads/release/python-351/",
"https://www.python.org/downloads/release/python-2711/",
"https://www.python.org/downloads/release/python-350/",
"https://www.python.org/downloads/release/python-2710/",
"https://www.python.org/downloads/release/python-343/",
"https://www.python.org/downloads/release/python-279/",
"https://www.python.org/downloads/release/python-342/",
"https://www.python.org/downloads/release/python-336/",
"https://www.python.org/downloads/release/python-326/",
"https://www.python.org/downloads/release/python-278/",
"https://www.python.org/downloads/release/python-277/",
"https://www.python.org/downloads/release/python-341/",
"https://www.python.org/downloads/release/python-340/",
"https://www.python.org/downloads/release/python-335/",
"https://www.python.org/downloads/release/python-334/",
"https://www.python.org/downloads/release/python-333/",
"https://www.python.org/downloads/release/python-276/",
"https://www.python.org/downloads/release/python-269/",
"https://www.python.org/downloads/release/python-325/",
"https://www.python.org/downloads/release/python-332/",
"https://www.python.org/downloads/release/python-275/",
"https://www.python.org/downloads/release/python-331/",
"https://www.python.org/downloads/release/python-274/",
"https://www.python.org/downloads/release/python-324/",
"https://www.python.org/downloads/release/python-330/",
"https://www.python.org/downloads/release/python-323/",
"https://www.python.org/downloads/release/python-268/",
"https://www.python.org/downloads/release/python-315/",
"https://www.python.org/downloads/release/python-273/",
"https://www.python.org/downloads/release/python-322/",
"https://www.python.org/downloads/release/python-321/",
"https://www.python.org/downloads/release/python-314/",
"https://www.python.org/downloads/release/python-272/",
"https://www.python.org/downloads/release/python-267/",
"https://www.python.org/downloads/release/python-256/",
"https://www.python.org/downloads/release/python-320/",
"https://www.python.org/downloads/release/python-271/",
"https://www.python.org/downloads/release/python-313/",
"https://www.python.org/downloads/release/python-266/",
"https://www.python.org/downloads/release/python-270/",
"https://www.python.org/downloads/release/python-312/",
"https://www.python.org/downloads/release/python-265/",
"https://www.python.org/downloads/release/python-255/",
"https://www.python.org/downloads/release/python-264/",
"https://www.python.org/downloads/release/python-263/",
"https://www.python.org/downloads/release/python-311/",
"https://www.python.org/downloads/release/python-310/",
"https://www.python.org/downloads/release/python-262/",
"https://www.python.org/downloads/release/python-301/",
"https://www.python.org/downloads/release/python-254/",
"https://www.python.org/downloads/release/python-246/",
"https://www.python.org/downloads/release/python-253/",
"https://www.python.org/downloads/release/python-261/",
"https://www.python.org/downloads/release/python-300/",
"https://www.python.org/downloads/release/python-260/",
"https://www.python.org/downloads/release/python-237/",
"https://www.python.org/downloads/release/python-245/",
"https://www.python.org/downloads/release/python-252/",
"https://www.python.org/downloads/release/python-251/",
"https://www.python.org/downloads/release/python-236/",
"https://www.python.org/downloads/release/python-244/",
"https://www.python.org/downloads/release/python-250/",
"https://www.python.org/downloads/release/python-243/",
"https://www.python.org/downloads/release/python-242/",
"https://www.python.org/downloads/release/python-241/",
"https://www.python.org/downloads/release/python-235/",
"https://www.python.org/downloads/release/python-240/",
"https://www.python.org/downloads/release/python-234/",
"https://www.python.org/downloads/release/python-233/",
"https://www.python.org/downloads/release/python-232/",
"https://www.python.org/downloads/release/python-231/",
"https://www.python.org/downloads/release/python-230/",
"https://www.python.org/downloads/release/python-223/",
"https://www.python.org/downloads/release/python-222/",
"https://www.python.org/downloads/release/python-221/",
"https://www.python.org/downloads/release/python-213/",
"https://www.python.org/downloads/release/python-220/",
"https://www.python.org/downloads/release/python-201/"
];

(async () => {
    const browser = await puppeteer.launch({ headless: true });
    console.log('Browser launched.');
    const results = []; // Array to store all the scraped data

    for (const url of urls) {
        let page;
        try {
            console.log(`Processing URL: ${url}`);
            page = await browser.newPage();
            await page.goto(url, { waitUntil: 'networkidle2', timeout: 60000 });

            // Wait for the table rows to appear
            await page.waitForSelector('.article-header~table tbody>tr', { timeout: 30000 });

            // Scrape table data
            const pageData = await page.evaluate(() => {
                const rows = document.querySelectorAll('.article-header~table tbody>tr');
                return Array.from(rows).map(row => {
                    const cells = row.querySelectorAll('td');
                    return {
                        version : document.querySelector(".page-title").innerText,
                        title: cells[0]?.querySelector('a')?.innerText || null,
                        downloadLink: cells[0]?.querySelector('a')?.href || null,
                        os: cells[1]?.textContent?.trim() || null,
                        description: cells[2]?.textContent?.trim() || null,
                        md5Hash: cells[3]?.textContent?.trim() || null,
                        size: cells[4]?.textContent?.trim() || null,
                        sigLink: cells[5]?.querySelector('a')?.href || null,
                        sigstoreLink: cells[6]?.querySelector('a')?.href || null,
                        spdxLink: cells[7]?.querySelector('a')?.href || null,
                    };
                });
            });

            console.log(`Extracted ${pageData.length} rows from ${url}`);
            results.push({ url, data: pageData });

        } catch (error) {
            console.error(`Error processing ${url}:`, error.message);
            results.push({ url, error: error.message, data: [] });
        } finally {
            if (page) await page.close();
        }
    }

    await browser.close();
    console.log('Browser closed.');

    // Save the results to a JSON file
    const outputFile = 'scraped_data.json';
    fs.writeFileSync(outputFile, JSON.stringify(results, null, 2));
    console.log(`Results saved to ${outputFile}`);
})();
