const puppeteer = require('puppeteer');
const fs = require('fs');

// List of channel URLs to scrape
const channelUrls = [
"https://www.youtube.com/@learnarabicwithasmae1",
"https://www.youtube.com/@nar291",
"https://www.youtube.com/@LearnArabicwithustazmahmoud",
"https://www.youtube.com/@ArabicPod101",
"https://www.youtube.com/@LearnArabicKhasu",
"https://www.youtube.com/@arabicblooms",
"https://www.youtube.com/@learnarabic_online",
"https://www.youtube.com/@LearnArabicwithRazan",
"https://www.youtube.com/@LearnArabicWithAmeen",
"https://www.youtube.com/@AlJazeeraLearningArabic",
"https://www.youtube.com/@Levelupurarabic",
"https://www.youtube.com/@LearnArabiclanguageinUrdu",
"https://www.youtube.com/@LearnLevantineArabic",
"https://www.youtube.com/@Step-By-StepArabic",
"https://www.youtube.com/@Arabicwithamina",
"https://www.youtube.com/@learnarabicwithmaria",
"https://www.youtube.com/@ArabicBurmeseWithAyisha",
"https://www.youtube.com/@Arabic101",
"https://www.youtube.com/@Learn3Arabic",
"https://www.youtube.com/@LetsLearnArabic",
"https://www.youtube.com/@ArabicwithHind",
"https://www.youtube.com/@learnarabicwithkenan",
"https://www.youtube.com/@learnmodernstandardarabic",
"https://www.youtube.com/@%D8%A7%D8%AA%D8%B9%D9%84%D9%85%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D9%87%D8%A8%D8%B3%D9%87%D9%88%D9%84%D9%87",
"https://www.youtube.com/@LearnArabicwithAJ",
"https://www.youtube.com/@mohamedelgaly87",
"https://www.youtube.com/@learnArabicwithAisha",
"https://www.youtube.com/@ARABICLANGUAGEACADEMY-DG",
"https://www.youtube.com/@learnarabicdaily3884",
"https://www.youtube.com/@LetsLearnArabic1",
"https://www.youtube.com/@EgyptianArabicMimo",
"https://www.youtube.com/@arabicwithsahar",
"https://www.youtube.com/@learnarabicwithmrs.hammoud9593",
"https://www.youtube.com/@hidayacenter",
"https://www.youtube.com/@LearnArabicAndEnglishwithHarun",
"https://www.youtube.com/@LearnArabicSameh",
"https://www.youtube.com/@arabicteacher1",
"https://www.youtube.com/@ArabicwithManar",
"https://www.youtube.com/@LearnArabicEveryDay-nq4rr",
"https://www.youtube.com/@learningwithheba",
"https://www.youtube.com/@LearningArabicMadeEasy",
"https://www.youtube.com/@eliteforlearningarabic",
"https://www.youtube.com/@learnarabicwithmiu",
"https://www.youtube.com/@learnarabicwithahmed5309",
"https://www.youtube.com/@LearnArabicwithEZ",
"https://www.youtube.com/@QasimRazviArabic",
"https://www.youtube.com/@LearnArabicSumi",
"https://www.youtube.com/@LearnArabicwithTahir",
"https://www.youtube.com/@rayanarabictv",
"https://www.youtube.com/@ArabicwithToqa",
"https://www.youtube.com/@arabic-alphabets",
"https://www.youtube.com/@LearnArabicWithLammy",
"https://www.youtube.com/@LearnArabicfrommovies-rq1pb",
"https://www.youtube.com/@LearnArabicQasid",
"https://www.youtube.com/@LearnArabic_with_Ali",
"https://www.youtube.com/@LearnArabicWithKawkab",
"https://www.youtube.com/@ArabicandTajweedwithIz",
"https://www.youtube.com/@learnarabicwithfaizy",
"https://www.youtube.com/@LearnArabicwithwajid",
"https://www.youtube.com/@learnarabicwithmohamednasr777",
"https://www.youtube.com/@learnarabicwithamal1285",
"https://www.youtube.com/@LearnArabicbyIdris-x3b",
"https://www.youtube.com/@LearnArabicwithMaha",
"https://www.youtube.com/@ArabicwithLoubnaDuymayan",
"https://www.youtube.com/@LearnArabic-qy7jt",
"https://www.youtube.com/@LearnArabicwithRaza",
"https://www.youtube.com/@learn_arabic_with_masud",
"https://www.youtube.com/@learningarabicisfun5209",
"https://www.youtube.com/@LearnArabicWithHamada",
"https://www.youtube.com/@ArabicWithOmar",
"https://www.youtube.com/@learnarabicwithmaryam",
"https://www.youtube.com/@HafizGhulamMustafa.",
"https://www.youtube.com/@arabicforbeginners3201",
"https://www.youtube.com/@LearnWithZakaria",
"https://www.youtube.com/@AnyArabic",
"https://www.youtube.com/@LearnArabic-y4e",
"https://www.youtube.com/@LearnArabicLanguage-1",
"https://www.youtube.com/@MadinahArabicTuition",
"https://www.youtube.com/@miladmunib",
"https://www.youtube.com/@arabiceasylearningchannelwithz",
"https://www.youtube.com/@Arabicles",
"https://www.youtube.com/@LearnArabicBySheikhAbdullah",
"https://www.youtube.com/@taalim_arabe",
"https://www.youtube.com/@missmarwasobhy",
"https://www.youtube.com/@learnarabicwithsoraya7653",
"https://www.youtube.com/@MyArabicJourneyWithMohammed",
"https://www.youtube.com/@learnarabicwithhana",
"https://www.youtube.com/@learnarabicbymuftinaseem1999",
"https://www.youtube.com/@AsmaAbdellah",
"https://www.youtube.com/@learnarabicwithnassramethod",
"https://www.youtube.com/@AlifBee_learnArabic",
"https://www.youtube.com/@LearnArabicthroughdrama",
"https://www.youtube.com/@MaramArabic",
"https://www.youtube.com/@lingodice-learnarabic5908",
"https://www.youtube.com/@LearnArabicMoviesCartoons",
"https://www.youtube.com/@LearnArabicwithMRafeynadwi",
"https://www.youtube.com/@Learn_Arabic_with_EyaKh",
"https://www.youtube.com/@learnArabicwithAilYousry",
"https://www.youtube.com/@LearnArabicwithMona",
"https://www.youtube.com/@learnarabicwithmike4175",
"https://www.youtube.com/@learn-arabic-forbeginners",
"https://www.youtube.com/@tutoromda",
"https://www.youtube.com/@arabicmadfun",
"https://www.youtube.com/@learnArabiceasy123",
"https://www.youtube.com/@Lets.LearnArabic",
"https://www.youtube.com/@learnarabicsimply",
"https://www.youtube.com/@LearnwithNoor",
"https://www.youtube.com/@talkarabictoday",
"https://www.youtube.com/@Learn-Arabic-Ahmed",
"https://www.youtube.com/@ahmadmuttaka9915",
"https://www.youtube.com/@LearnSudaneseArabicwithDaff",
"https://www.youtube.com/@KiranKhalid-u8w",
"https://www.youtube.com/@LearnArabicWithMostafa-xo7rd",
"https://www.youtube.com/@letslearnarabic2656",
"https://www.youtube.com/@LearnArabicWithAbbassia",
"https://www.youtube.com/@LearnArabicwithme100",
"https://www.youtube.com/@AbdrwahmanDysoni",
"https://www.youtube.com/@%D8%A7%D9%84%D8%A3%D8%B3%D8%AA%D8%A7%D8%B0%D8%B9%D8%A8%D8%AF%D8%A7%D9%84%D8%AE%D8%A7%D9%84%D9%82_%D8%A7%D9%8A%D9%87%D8%A7%D8%A8",
"https://www.youtube.com/@learnarabicwithsalem9021",
"https://www.youtube.com/@MudarrisSulaimanAli-M2S",
"https://www.youtube.com/@NehalistaArabic",
"https://www.youtube.com/@spokenlevantinelebanesearabic",
"https://www.youtube.com/@LearnArabicwithZed",
"https://www.youtube.com/@learnarabic1",
"https://www.youtube.com/@learnarabicwithminhaj",
"https://www.youtube.com/@Learnarabicwithkhaled",
"https://www.youtube.com/@learnarabicgrammar-8747",
"https://www.youtube.com/@learnarabicwithhadeer8378",
"https://www.youtube.com/@AliBabaABEC",
"https://www.youtube.com/@LearnArabicwithBaker",
"https://www.youtube.com/@AbdulmalikAbubakar-jg4mz",
"https://www.youtube.com/@LearnArabicwithHope",
"https://www.youtube.com/@LearnArabicWithHusain",
"https://www.youtube.com/@LearnArabicWithNasih",
"https://www.youtube.com/@learnArabicwithRamzia",
"https://www.youtube.com/@ArabicShehab",
"https://www.youtube.com/@LearnArabicLanguage123",
"https://www.youtube.com/@LetsLearnArabicWithIffi2007",
"https://www.youtube.com/@learnarabicacademybh3051",
"https://www.youtube.com/@learnarabicwithbilal4473",
"https://www.youtube.com/@learnarabicwithenglish445",
"https://www.youtube.com/@ArabicWithHeidi",
"https://www.youtube.com/@TalkArabic",
"https://www.youtube.com/@learnWfun",
"https://www.youtube.com/@Arabicwithbhatti",
"https://www.youtube.com/@timetolearnarabic1124",
"https://www.youtube.com/@PrintandlearnArabic",
"https://www.youtube.com/@LearnArabicwithMarwaMousa",
"https://www.youtube.com/@Musfirahhassan",
"https://www.youtube.com/@kamal_learn_arabic_bd",
"https://www.youtube.com/@ArabicwithMasud",
"https://www.youtube.com/@learnArabicwithHassannadwi",
"https://www.youtube.com/@learnarabicwithdina",
"https://www.youtube.com/@globallearnarabicwithgramm7348",
"https://www.youtube.com/@LearnArabicWithNader",
"https://www.youtube.com/@LearnArabicwithMuhammad-s2332b",
"https://www.youtube.com/@arabicwithshoaib5543",
"https://www.youtube.com/@ibrahim.arabic",
"https://www.youtube.com/@arab_ic94",
"https://www.youtube.com/@pathtoarabictv",
"https://www.youtube.com/@Tanveer_ahmad_shah",
"https://www.youtube.com/@Linguamid",
"https://www.youtube.com/@learnarabicwithshaban",
"https://www.youtube.com/@eArabicLearning.",
"https://www.youtube.com/@learnarabic4931",
"https://www.youtube.com/@learnarabiconlinewithiqbal6751",
"https://www.youtube.com/@learnarabicsaad",
"https://www.youtube.com/@LearnArabicWithAmal",
"https://www.youtube.com/@arsalanarabic",
"https://www.youtube.com/@learnarabic5935",
"https://www.youtube.com/@LearnArabicwithRasheid",
"https://www.youtube.com/@LearnarabicwithShoaib928",
"https://www.youtube.com/@Learn0Arabic",
"https://www.youtube.com/@LearnArabic_English1",
"https://www.youtube.com/@larabiclquran",
"https://www.youtube.com/@LearnarabicInfo",
"https://www.youtube.com/@LearnArabicWithSK",
"https://www.youtube.com/@LearnArabicwithAkram",
"https://www.youtube.com/@shaikrahmat786",
"https://www.youtube.com/@learn_arabic_with_eqra",
"https://www.youtube.com/@learnarabiclanguage863",
"https://www.youtube.com/@ArabicbyImransir",
"https://www.youtube.com/@dr.mahasweis-learnarabic",
"https://www.youtube.com/@learnarabiclanguage8931",
"https://www.youtube.com/@ArabicForEveryone-e2y",
"https://www.youtube.com/@MostafaDahy-et5ji",
"https://www.youtube.com/@BilalAwan-ex5gk",
"https://www.youtube.com/@LearnArabicWithZahid",
"https://www.youtube.com/@learnarabicalfaz4164",
"https://www.youtube.com/@learnarabic12",
"https://www.youtube.com/@ReadwithTajweeed",
"https://www.youtube.com/@learnarabic7370",
"https://www.youtube.com/@LearnArabicwithYumna",
"https://www.youtube.com/@LearnArabicWithAi",
"https://www.youtube.com/@learn_arabic",
"https://www.youtube.com/@learnarabicwithjana3870",
"https://www.youtube.com/@learnarabicforkid",
"https://www.youtube.com/@learnarabicwithsoso7050",
"https://www.youtube.com/@LearnArabicwithNuh",
"https://www.youtube.com/@learnArabic786",
"https://www.youtube.com/@HaseebAfzal_",
"https://www.youtube.com/@SaeedNawaz-c9b",
"https://www.youtube.com/@Learnarabicwithme-v3k",
"https://www.youtube.com/@LearnArabicFast_",
"https://www.youtube.com/@learnarabicwithyourfavorit4735",
"https://www.youtube.com/@varshanaik207",
"https://www.youtube.com/@LearnArabicWithSheriff",
"https://www.youtube.com/@moutooz",
"https://www.youtube.com/@Afreen-221",
"https://www.youtube.com/@MarwaMahmoud-o9w",
"https://www.youtube.com/@learnarabic7642",
"https://www.youtube.com/@LearnArabicwithRaed-qu8zn",
"https://www.youtube.com/@LearnArabicWithHameed",
"https://www.youtube.com/@learnarabicnow8370",
"https://www.youtube.com/@learnarabic1245",
"https://www.youtube.com/@KidzyJourneytoArabic",
"https://www.youtube.com/@CartoonWithMe592",
"https://www.youtube.com/@learnarabicwithfaten",
"https://www.youtube.com/@LearnArabicWithRotaniyy",
"https://www.youtube.com/@arabicandQuranlearning",
"https://www.youtube.com/@learnarabiclanguage6048",
"https://www.youtube.com/@learnarabiceasily9863",
"https://www.youtube.com/@learnarabictounderstandthe931",
"https://www.youtube.com/@asmrcooking-hz7eu",
"https://www.youtube.com/@learnarabiclanguagewithmov3869",
"https://www.youtube.com/@YousufPuttanikkadan-m2g",
"https://www.youtube.com/@Learnarabic-ts6rs",
"https://www.youtube.com/@learning_Arabic",
"https://www.youtube.com/@LearnArabicWithShaikhAbuAnas",
"https://www.youtube.com/@LearnArabicSIWER",
"https://www.youtube.com/@LearnArabictoReadQuran-hm3qq",
"https://www.youtube.com/@Learn_Arabic_With_Maria",
"https://www.youtube.com/@learningarabiclanguage810",
"https://www.youtube.com/@Sayeedahmedindia",
"https://www.youtube.com/@alheralearnarabic",
"https://www.youtube.com/@learnarabic6661",
"https://www.youtube.com/@learnarabic473",
"https://www.youtube.com/@learnarabicforkidswithsumi8540",
"https://www.youtube.com/@learnarabic7880",
"https://www.youtube.com/@mdayatullahhanafi6198",
"https://www.youtube.com/@learnarabicwithnaranj3990",
"https://www.youtube.com/@learnarabicasafamily6224",
"https://www.youtube.com/@learn_arabic_101",
"https://www.youtube.com/@learnarabic6647",
"https://www.youtube.com/@learnarabiclanguage7699",
"https://www.youtube.com/@learnarabiceasily8639",
"https://www.youtube.com/@learnarabicwithshady7624",
"https://www.youtube.com/@NewApproachToLearnArabic",
"https://www.youtube.com/@LearnArabicwithFatima",
"https://www.youtube.com/@LearnArabicforfree-i7o",
"https://www.youtube.com/@LearnArabicLanguageandQuraan",
"https://www.youtube.com/@learnarabic5632",
"https://www.youtube.com/@ArabicWithBroAkmaltu",
"https://www.youtube.com/@learn_arabic_every_day",
"https://www.youtube.com/@ArabicLanguageJourney",
"https://www.youtube.com/@LearnArabicEasyWay",
"https://www.youtube.com/@Saad-wj8f",
"https://www.youtube.com/@LearnArabicwithNardjes",
"https://www.youtube.com/@LearnArabicEnglish",
"https://www.youtube.com/@learnarabicandquranonline",
"https://www.youtube.com/@LearnArabicWithme-fk9cr",
"https://www.youtube.com/@LearnArabicnEnglish",
"https://www.youtube.com/@Benyamin-mr4ib",
"https://www.youtube.com/@LearnArabicwithHend",
"https://www.youtube.com/@LEARNARABICWITHUMMEHAFSA-rj7dl",
"https://www.youtube.com/@arabicstorytranslatedineng3328",
"https://www.youtube.com/@learnarabiclanguage1037",
"https://www.youtube.com/@qamar8946",
"https://www.youtube.com/@learnarabic5616",
"https://www.youtube.com/@ShafiqAhmadarabic",
"https://www.youtube.com/@ahmadhamdi-bn9hn",
"https://www.youtube.com/@Habibihangout",
"https://www.youtube.com/@LearnArabicwithRamzi-f9u",
"https://www.youtube.com/@mai_online_academy",
"https://www.youtube.com/@MudarrisSulaimanAli-M2A",
"https://www.youtube.com/@LearnArabic4",
"https://www.youtube.com/@mohamedabdelazime3852",
"https://www.youtube.com/@learnarabic4277",
"https://www.youtube.com/@marouaamari7421",
"https://www.youtube.com/@learnarabiclanguageinurdu4278",
"https://www.youtube.com/@learn-arabic",
"https://www.youtube.com/@learnarabicacademynet",
"https://www.youtube.com/@LearnArabicFromQuran",
"https://www.youtube.com/@learnarabicwithsuhail5525",
"https://www.youtube.com/@HowtolearnArabic-x3k",
"https://www.youtube.com/@LAWAMAR",
"https://www.youtube.com/@LearnArabicwithAbdulJabbar",
"https://www.youtube.com/@PlayandLearnArabicwithKokobird",
"https://www.youtube.com/@learnwithabdurrahman9200",
"https://www.youtube.com/@LEARNARABICWITHMUHAMMAD-hf2zd",
"https://www.youtube.com/@LearnArabicWithUsama",
"https://www.youtube.com/@learnarabicwithsabry-tu5vu",
"https://www.youtube.com/@learnarabicwithbrainflyaca5846",
"https://www.youtube.com/@LearnArabicwithT.Mahmoud",
"https://www.youtube.com/@LearnArabicwithPapso",
"https://www.youtube.com/@AskAbuHafs",
"https://www.youtube.com/@learnarabicwithease0392",
"https://www.youtube.com/@LearnArabiceasily-i7d",
"https://www.youtube.com/@learnarabiclanguageonline",
"https://www.youtube.com/@OsmanGony-ob6zw",
"https://www.youtube.com/@learnarabicquranonline5189",
"https://www.youtube.com/@mammeridouaa",
"https://www.youtube.com/@isabp2003",
"https://www.youtube.com/@%D8%AF..%D9%85%D8%AD%D9%85%D8%AF%D8%B3%D8%B9%D9%8A%D8%AF",
"https://www.youtube.com/@user-gz9mq8vh7y",
"https://www.youtube.com/@LearnArabic-zz4rh",
"https://www.youtube.com/@LearnArabictoEnglishwithDrRiaz",
"https://www.youtube.com/@al4nasapp",
"https://www.youtube.com/@learnarabiconline7263",
"https://www.youtube.com/@LearnArabicwithAli-me6bg",
"https://www.youtube.com/@learnarabic2752",
"https://www.youtube.com/@learnarabic9052",
"https://www.youtube.com/@learnarabic8360",
"https://www.youtube.com/@iliketolearnarabic7333",
"https://www.youtube.com/@LearnArabicwithLena",
"https://www.youtube.com/@learnarabicquranonlinewith8836",
"https://www.youtube.com/@learnarabiceasily3518",
"https://www.youtube.com/@learnarabicwithnoman",
"https://www.youtube.com/@learnarabic2734",
"https://www.youtube.com/@LearnArabicCommunity",
"https://www.youtube.com/@%D8%B1%D8%AD%D9%84%D8%AA%D9%8A%D8%A5%D9%84%D9%89%D8%A7%D9%84%D9%84%D8%BA%D8%A9%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9",
"https://www.youtube.com/@learn_arabic_with_fun",
"https://www.youtube.com/@LearnArabicwithKhalid-d4m",
"https://www.youtube.com/@learnarabicandenglish3789",
"https://www.youtube.com/@LearnArabicwithFriday",
"https://www.youtube.com/@Non_Arab_Speakers",
"https://www.youtube.com/@learnarabiclanguagefast9227",
"https://www.youtube.com/@LearnArabicwithSiraj",
"https://www.youtube.com/@learnarabicemirati959",
"https://www.youtube.com/@abdullahiabdulazeez3869",
"https://www.youtube.com/@learnarabicwithnasir",
"https://www.youtube.com/@Wafaa789",
"https://www.youtube.com/@arabiclanguage512",
"https://www.youtube.com/@LearnTajweedKaunainIbraheem",
"https://www.youtube.com/@radwasadek1",
"https://www.youtube.com/@LearnArabic-z9s",
"https://www.youtube.com/@rehamosman3564",
"https://www.youtube.com/@learn93-d5p",
"https://www.youtube.com/@LearnArabicSlang-qy3vb",
"https://www.youtube.com/@learnarabic3638",
"https://www.youtube.com/@learnarabicwithahmed1",
"https://www.youtube.com/@LearningArabicWithShakhzod",
"https://www.youtube.com/@LearnArabicwithJobayer",
"https://www.youtube.com/@LearnArabic5",
"https://www.youtube.com/@learnarabic9079",
"https://www.youtube.com/@LetslearnArabic2024",
"https://www.youtube.com/@mehboobkhan_04",
"https://www.youtube.com/@learn_arabic_easily",
"https://www.youtube.com/@arabiclang",
"https://www.youtube.com/@learning-s9e",
"https://www.youtube.com/@sibawayonline",
"https://www.youtube.com/@LearnArabic-we7lw",
"https://www.youtube.com/@learnarabiconline9254",
"https://www.youtube.com/@learnarabicwithasteer",
"https://www.youtube.com/@Arabic.learn.1",
"https://www.youtube.com/@learnArabicwithme-ej4kw",
"https://www.youtube.com/@Arabio2003",
"https://www.youtube.com/@Learnarabicwithme-g1k",
"https://www.youtube.com/@youceffff",
"https://www.youtube.com/@LearnArabicwithSara",
"https://www.youtube.com/@learnarabiclanguages5951",
"https://www.youtube.com/@learnarabic132",
"https://www.youtube.com/@LearnArabicwithNasruddin",
"https://www.youtube.com/@learnarabiclanguage2683",
"https://www.youtube.com/@anisurrahmanar-ew7zc",
"https://www.youtube.com/@bakrahmed123",
"https://www.youtube.com/@virtualteacherlearnarabic1649",
"https://www.youtube.com/@LearnArabicwithHindi786",
"https://www.youtube.com/@learnarabicwithwlkam1398",
"https://www.youtube.com/@learnarabic8899",
"https://www.youtube.com/@ArabicLearningMadeEasy",
"https://www.youtube.com/@arabicwithelnoor",
"https://www.youtube.com/@ArabDiction",
"https://www.youtube.com/@learnarabic7811",
"https://www.youtube.com/@learnarabicwithhany8445",
"https://www.youtube.com/@learnarabic-mm9ys",
"https://www.youtube.com/@learnarabiconline9826",
"https://www.youtube.com/@learnarabic2618",
"https://www.youtube.com/@itsarabic.com6",
"https://www.youtube.com/@LearnArabicEasy-bv1ej",
"https://www.youtube.com/@huffazarabicinstitute543",
"https://www.youtube.com/@learnarabicwithfatimazahra7491",
"https://www.youtube.com/@LearnArabicwithtamil",
"https://www.youtube.com/@AutrojAcademyLearnArabic",
"https://www.youtube.com/@ahmedwaheed5090",
"https://www.youtube.com/@Zaina188",
"https://www.youtube.com/@LearnArabicwithNourhan",
"https://www.youtube.com/@LetsLearnArabic-x5h",
"https://www.youtube.com/@learnarabicwithmostafa",
"https://www.youtube.com/@TheArabiker",
"https://www.youtube.com/@LearnArabicwithUzair111",
"https://www.youtube.com/@learnarabiceasy-uz5cx",
"https://www.youtube.com/@LearnArabic-x1y",
"https://www.youtube.com/@easy_arabic_master",
"https://www.youtube.com/@learnarabicwithmubeen",
"https://www.youtube.com/@arabicwithamir",
"https://www.youtube.com/@islamictv441",
"https://www.youtube.com/@learnarabicwitheman912",
"https://www.youtube.com/@learnarabiceasily7010",
"https://www.youtube.com/@arabic.with.mahmoud",
"https://www.youtube.com/@LearnArabicwithEdward",
"https://www.youtube.com/@learnarabic6497",
"https://www.youtube.com/@learnarabicwithenglish3872",
"https://www.youtube.com/@learnarabicbylevels3404",
"https://www.youtube.com/@learnarabictoreadquran7893",
"https://www.youtube.com/@learnarabicquranwithsiraj1236",
"https://www.youtube.com/@LEARNARABICWITHTVSERIES2",
"https://www.youtube.com/@katibammar3134",
"https://www.youtube.com/@Quranicarabic001",
"https://www.youtube.com/@learnarabicezzbassyouni6779",
"https://www.youtube.com/@Learn_arabicwithme",
"https://www.youtube.com/@learnarabicwithemad5926",
"https://www.youtube.com/@OlamilekanYusuf-y1r",
"https://www.youtube.com/@learnarabicwithsally6550",
"https://www.youtube.com/@learnarabicwithsamaan7412",
"https://www.youtube.com/@learnarabiconlinecourse162",
"https://www.youtube.com/@hrfapplearnarabic-2209",
"https://www.youtube.com/@Learnarabicwithme838",
"https://www.youtube.com/@learnarabicwithzafar",
"https://www.youtube.com/@AmyAli-hh5lw",
"https://www.youtube.com/@learnarabicwithdialogues-ol7mz",
"https://www.youtube.com/@Arabiclearning2020",
"https://www.youtube.com/@arabiy-xyz",
"https://www.youtube.com/@learnarabicwithfatiha7118",
"https://www.youtube.com/@Ahlen_ar",
"https://www.youtube.com/@Wissamoarabic",
"https://www.youtube.com/@RSjagun2024",
"https://www.youtube.com/@learnarabicwithzfamily897",
"https://www.youtube.com/@learn-arabic-online",
"https://www.youtube.com/@learnarabicwithkareem",
"https://www.youtube.com/@shehir9203",
"https://www.youtube.com/@learnarabicfornonnativespe5521",
"https://www.youtube.com/@learnarabicwithana",
"https://www.youtube.com/@AshrafAshaa",
"https://www.youtube.com/@learnarabiclanguagewithme8460",
"https://www.youtube.com/@letslearnarabic7880",
"https://www.youtube.com/@learnarabiceasily4148",
"https://www.youtube.com/@LearnArabicwithMS",
"https://www.youtube.com/@learnarabiclanguagebyar",
"https://www.youtube.com/@gamolalearnArabic1986",
"https://www.youtube.com/@learnarabicwithq1934",
"https://www.youtube.com/@learnarabicenglishbangla",
"https://www.youtube.com/@learn_arabicwithkaka",
"https://www.youtube.com/@LearnArabicWithHusam",
"https://www.youtube.com/@LearnArabicWithMohammad",
"https://www.youtube.com/@learnarabicwithhashem6948",
"https://www.youtube.com/@learnarabic.289",
"https://www.youtube.com/@LearnArabicWithmr",
"https://www.youtube.com/@learnarabiceasybusy-vs3sq",
"https://www.youtube.com/@learnarabicwithlozy4262",
"https://www.youtube.com/@LearnArabicwithMsFatma",
"https://www.youtube.com/@LearnArabicWords24-7",
"https://www.youtube.com/@learnarabicwithtalaa",
"https://www.youtube.com/@learnarabicwithmuhammad2181",
"https://www.youtube.com/@LearnArabicSimple",
"https://www.youtube.com/@learningarabicwords2512",
"https://www.youtube.com/@easytolearnarabic651",
"https://www.youtube.com/@simpleArabic11",
"https://www.youtube.com/@Learn.Arabic.Taesol",
"https://www.youtube.com/@learnarabicwithmorabiaa8097",
"https://www.youtube.com/@learnarabic001",
"https://www.youtube.com/@ArmanNadwi",
"https://www.youtube.com/@-Learnarabic-gl2hl",
"https://www.youtube.com/@ayeshacreations226",
"https://www.youtube.com/@arabic-teacher",
"https://www.youtube.com/@apprendrelarabelearnarabic-d8w",
"https://www.youtube.com/@learnarabic-learnquran6092",
"https://www.youtube.com/@learnarabicwithhatem1713",
"https://www.youtube.com/@letslearnarabic1418",
"https://www.youtube.com/@arabicwithnawaz",
"https://www.youtube.com/@ilearnarabic344",
"https://www.youtube.com/@MvAbdullah-r6u",
"https://www.youtube.com/@learnarabicthroughurdu2703",
"https://www.youtube.com/@Katchi.Learn.Arabic",
"https://www.youtube.com/@learnarabicwithsara9481",
"https://www.youtube.com/@newinnovativementors7089",
"https://www.youtube.com/@learnarabic2580",
"https://www.youtube.com/@learnarabicwithalisha",
"https://www.youtube.com/@learnarabicwithrama8723",
"https://www.youtube.com/@aktub-learnarabic-5049",
"https://www.youtube.com/@learnarabicsimply4816",
"https://www.youtube.com/@LearnArabicAcademy",
"https://www.youtube.com/@learnarabicandturkishwithm9313",
"https://www.youtube.com/@mylittleworld3056",
"https://www.youtube.com/@soundsoftheworld0",
"https://www.youtube.com/@learnarabicinhindi7199",
"https://www.youtube.com/@LearnArabicEasily-xn1sd",
"https://www.youtube.com/@learnarabicchannel1832",
"https://www.youtube.com/@Arabic_with_Ali",
"https://www.youtube.com/@arabic.urdu_language.",
"https://www.youtube.com/@learnarabicwithareeba4304",
"https://www.youtube.com/@Assnarabibolchal",
"https://www.youtube.com/@travellearnarabictalklikea9703",
"https://www.youtube.com/@learnarabicfunnychannel5436",
"https://www.youtube.com/@learnarabicwithrakesh",
"https://www.youtube.com/@learnarabicwithnagmaandcal4388",
"https://www.youtube.com/@Foyshal7070",
"https://www.youtube.com/@Learnarabicwithahmedfahmy",
"https://www.youtube.com/@Arabic.34",
"https://www.youtube.com/@%D8%B9%D8%A8%D8%A7%D8%AF%D8%A7%D9%84%D8%B1%D8%AD%D9%85%D8%A7%D9%86-%D8%B49%D8%B5",
"https://www.youtube.com/@MinHuruf",
"https://www.youtube.com/@AhmedSalahLanguages",
"https://www.youtube.com/@C.B.A.gallery",
"https://www.youtube.com/@Arabic%E3%83%A1%E3%83%87%E3%82%A3%E3%82%A2.%E3%82%A2%E3%83%A9%E3%83%93%E3%82%A2%E8%AA%9E.%E8%A6%B3%E5%85%89",
"https://www.youtube.com/@Inspireedubymajidsir",
"https://www.youtube.com/@Abdullahiyusuf-l5v",
"https://www.youtube.com/@kids.easy.fast.education",
"https://www.youtube.com/@HennaMehndiDesignswithNaina",
"https://www.youtube.com/@learnegyptianlanguage2280",
"https://www.youtube.com/@Arabic-AB",
"https://www.youtube.com/@Noor-Al-Quran-g9l",
"https://www.youtube.com/@LEARNLANGUAGEtv-l5c",
"https://www.youtube.com/@AyaSobhy-Arabicteacher",
"https://www.youtube.com/@arjunkumarrajpoot6525",
"https://www.youtube.com/@ARIFTV-qo6xu",
"https://www.youtube.com/@ArabicInsights-b1k",
"https://www.youtube.com/@IslamicHub-q2f",
"https://www.youtube.com/@IslamInTheUK",
"https://www.youtube.com/@Channel.rumaysa",
"https://www.youtube.com/@SagerSons",
"https://www.youtube.com/@Quran-AL-ziker-studio786",
"https://www.youtube.com/@arabicmaster386",
"https://www.youtube.com/@StartingLevelZero",
"https://www.youtube.com/@Calligraphy.arabic2024",
"https://www.youtube.com/@mrssultanaman1737",
"https://www.youtube.com/@BabySharkKidsAlotsofSongsSA",
"https://www.youtube.com/@codewithmezo",
"https://www.youtube.com/@Ahmed-xbt",
"https://www.youtube.com/@MasjidOmaryTandur",
"https://www.youtube.com/@ZabihiCalligraphy786",
"https://www.youtube.com/@Arabanion",
"https://www.youtube.com/@Learndesignwithziya",
"https://www.youtube.com/@ZooZoospaceTV-i9i",
"https://www.youtube.com/@Mrlanguages-7languages2learn",
"https://www.youtube.com/@IslamicvideosWithArooj",
"https://www.youtube.com/@NewTikTok-u7j",
"https://www.youtube.com/@Easy-Arabic2024",
"https://www.youtube.com/@lyndsayalz",
"https://www.youtube.com/@letresor2596",
"https://www.youtube.com/@IslamDharm1",
"https://www.youtube.com/@LearningWithAlam-99k",
"https://www.youtube.com/@Kainath-islam786",
"https://www.youtube.com/@SkillMentor-16",
"https://www.youtube.com/@tv.hindikahaniya",
"https://www.youtube.com/@Hindi.kahaniya-com",
"https://www.youtube.com/@HindiSeArabiSikhne",
"https://www.youtube.com/@2ndHistory2ah",
"https://www.youtube.com/@RabbanaQuran",
"https://www.youtube.com/@Os14you-edu",
"https://www.youtube.com/@quranfirdawsenglish",
"https://www.youtube.com/@KOOKOOTVKids-z7g",
"https://www.youtube.com/@RAEES-y8c",
"https://www.youtube.com/@CalliArtStudio",
"https://www.youtube.com/@KaktosVibess",
"https://www.youtube.com/@AllamaAzhari",
"https://www.youtube.com/@Islamictravel568",
"https://www.youtube.com/@ShahinaDadapir",
"https://www.youtube.com/@CalligraphyLOVER-888",
"https://www.youtube.com/@MariamMohamed-tg4yx",
"https://www.youtube.com/@QARIBASHIRARKANI1980",
"https://www.youtube.com/@mohdraza-yo6vv",
"https://www.youtube.com/@TheArtisticTouch-b3q",
"https://www.youtube.com/@786Qurran",
"https://www.youtube.com/@mehandicreationlearn9694",
"https://www.youtube.com/@%D9%87%D9%8A%D8%AB%D9%85-%D8%B5%D8%A7%D9%81%D9%8A",
"https://www.youtube.com/@Islam360-x8z",
"https://www.youtube.com/@hindi_sexstory",
"https://www.youtube.com/@Islamicmotivationalspeech-f8d",
"https://www.youtube.com/@ReadQuran-j8h",
"https://www.youtube.com/@DrZakirNai-x4v",
"https://www.youtube.com/@SuraRehman",
"https://www.youtube.com/@Loveislamrealislam2"
];

(async () => {
    const browser = await puppeteer.launch({ headless: true });
    console.log('Browser launched.');

    const results = []; // Store the final results

    for (const channelUrl of channelUrls) {
        let page;
        try {
            console.log(`Navigating to channel: ${channelUrl}/playlists`);
            
            // Create a new page
            page = await browser.newPage();
            await page.goto(`${channelUrl}/playlists`, { waitUntil: 'networkidle2', timeout: 60000 });

            // Scroll to the bottom to load all playlists
            let previousHeight = 0;
            let retries = 5; // Retry limit to stop scrolling if no new content is loaded
            while (retries > 0) {
                const newHeight = await page.evaluate(() => {
                    window.scrollBy(0, window.innerHeight);
                    return document.documentElement.scrollHeight;
                });

                if (newHeight === previousHeight) {
                    retries--;
                } else {
                    retries = 5; // Reset retries if new content is loaded
                }
                previousHeight = newHeight;
                await page.waitForTimeout(1000); // Wait for content to load
            }

            // Wait for playlists to be visible
            await page.waitForSelector('a[href*="/playlist?list="]', { timeout: 30000 });

            // Extract channel title
            const channelTitle = await page.evaluate(() => {
                const titleElement = document.querySelector('meta[property="og:title"]') || 
                                     document.querySelector('title');
                return titleElement ? titleElement.content || titleElement.textContent : 'Unknown Title';
            });
            console.log(`Channel Title: ${channelTitle}`);

            // Extract playlist URLs
            const playlists = await page.evaluate(() => {
                return Array.from(document.querySelectorAll('a[href*="/playlist?list="]'))
                    .map(link => `https://www.youtube.com${link.getAttribute('href')}`)
                    .filter((v, i, a) => a.indexOf(v) === i); // Remove duplicates
            });
            console.log(`Found ${playlists.length} playlists.`);

            // Add to results
            results.push({
                title: channelTitle,
                url: channelUrl,
                playlists,
            });

        } catch (error) {
            console.error(`Error processing ${channelUrl}:`, error.message);
            results.push({
                title: 'Error fetching channel',
                url: channelUrl,
                playlists: [],
            });
        } finally {
            if (page) await page.close();
        }
    }

    // Save the results to a JSON file
    const outputFile = 'channels_with_playlists.json';
    fs.writeFileSync(outputFile, JSON.stringify(results, null, 2));
    console.log(`Results saved to ${outputFile}`);

    await browser.close();
    console.log('Browser closed.');
})();
